#!/bin/sh

extensions="-markdown_in_html_blocks-smart+tex_math_dollars+implicit_figures+link_attributes+tex_math_single_backslash+header_attributes"

cat book/*.md > html/book.md
pandoc html/book.md -fmarkdown$extensions -o html/book.html --ascii
cat html/template.html html/book.html > html/index.html
del /f /q html/book.html
del /f /q html/book.md
